AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyNewEventsRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Test Events Rule
      Name: !Ref check
      EventPattern:
        source:
          - aws.ec2
      State: ENABLED
